fixed_frame: "sensor_link"
human_frame: "twr_position"
use_3d: false
target: "DA12"

ids: [
  "5722",
  "5A84",
  "C4B5",
  "C694",
]

positions: [
  #x,y,z
  0.655, 0.495, 0.09,
  0.05, 0.495, 0.09,
  0.05, -0.495, 0.09,
  0.655, -0.495, 0.09,
]

calibration: [
  0, 0, 1, 0,
  0, 0, 1, 0,
  0, 0, 1, 0,
  0, 0, 1, 0,
]